sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t mshahomar/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mshahomar/react-test npm run test -- --coverage

after_success:
  - docker build -t mshahomar/multi-docker-client ./client
  - docker build -t mshahomar/multi-docker-nginx ./nginx
  - docker build -t mshahomar/multi-docker-server ./server
  - docker build -t mshahomar/multi-docker-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and push it to docker hub
  - docker push mshahomar/multi-docker-client
  - docker push mshahomar/multi-docker-nginx
  - docker push mshahomar/multi-docker-server
  - docker push mshahomar/multi-docker-worker